ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    two_d_mode: true # Forzamos a que ignore variaciones en Z, Roll y Pitch (robot 2D)
    publish_frame_id: true

    odom_frame: odom
    base_link_frame: base_footprint
    world_frame: odom # El marco local de estimación es odom

    publish_tf: true

    # Configuración del sensor 1: Odometría de las ruedas
    odom0: /wheel_odom
    odom0_config: [false,  false,  false, # x,  y,  z
                   false, false, false,  # roll, pitch, yaw
                   true,  true,  false, # vx, vy, vz
                   false, false, false,  # vroll, vpitch, vyaw
                   false, false, false]  # ax, ay, az
    odom0_differential: false

    # Configuración del sensor 2: IMU
    imu0: /imu/data_raw # Asegúrate de que este sea el tópico de tu IMU en Gazebo
    imu0_config: [false, false, false, # x,  y,  z
                  false, false, true, # roll, pitch, yaw
                  false, false, false, # vx, vy, vz
                  false, false, true, # vroll, vpitch, vyaw 
                  false, false, false] # ax, ay, az 
    imu0_differential: false
    imu0_relative: true # Toma la orientación inicial del IMU como 0